/**
 * @file
 * Conditional field visibility behaviors for node edit forms.
 *
 */
(function ($, Drupal, drupalSettings, once) {
  'use strict';

  /**
   * Converts a field group machine name into its DOM element ID.
   *
   * @example
   *   group_course_objectives → edit-group-course-objectives
   *
   * @param {string} group
   *   Field group machine name.
   * @return {string}
   *   Corresponding DOM element ID, without the leading '#'.
   */
  function groupToElementId(group) {
    return 'edit-' + group.replace(/_/g, '-');
  }

  /**
   * Converts a field machine name into its wrapper element DOM ID.
   *
   * @example
   *   field_venue → edit-field-venue-wrapper
   *
   * @param {string} field
   *   Field machine name.
   * @return {string}
   *   Corresponding wrapper DOM element ID, without the leading '#'.
   */
  function fieldToElementId(field) {
    return 'edit-' + field.replace(/_/g, '-') + '-wrapper';
  }

  /**
   * Hides field group panes and their corresponding horizontal tab links.
   *
   * Both the content pane and the tab anchor (matched by href) are hidden
   * so the tab does not remain visible in the tab bar when its content
   * is not relevant.
   *
   * @param {Array<string>} groups
   *   Field group machine names to hide.
   */
  function hideGroupDetails(groups) {
    groups.forEach(function (group) {
      let id = '#' + groupToElementId(group);
      $(id).hide();
      $('a[href="' + id + '"]').hide();
    });
  }

  /**
   * Shows field group panes and their corresponding horizontal tab links.
   *
   * Reverses the effect of hideGroupDetails() for the given groups.
   *
   * @param {Array<string>} groups
   *   Field group machine names to show.
   */
  function showGroupDetails(groups) {
    groups.forEach(function (group) {
      let id = '#' + groupToElementId(group);
      $(id).show();
      $('a[href="' + id + '"]').show();
    });
  }

  /**
   * Hides individual field wrapper elements.
   *
   * Targets the outer wrapper div generated by Drupal for each field
   * (e.g. #edit-field-venue-wrapper), not the field widget itself.
   *
   * @param {Array<string>} fields
   *   Field machine names whose wrappers should be hidden.
   */
  function hideFieldWrapper(fields) {
    fields.forEach(function (field) {
      let id = '#' + fieldToElementId(field);
      $(id).hide();
    });
  }

  /**
   * Shows individual field wrapper elements.
   *
   * Reverses the effect of hideFieldWrapper() for the given fields.
   *
   * @param {Array<string>} fields
   *   Field machine names whose wrappers should be shown.
   */
  function showFieldWrapper(fields) {
    fields.forEach(function (field) {
      let id = '#' + fieldToElementId(field);
      $(id).show();
    });
  }

  /**
   * Applies form UI visibility based on the selected training structure.
   *
   * Reads the current value of the training structure select and toggles
   * two sets of field groups and fields accordingly:
   *
   *  - "instance": show instance groups/fields, hide main groups/fields.
   *  - (any other value): show main groups/fields, hide instance groups/fields.
   *
   * After updating visibility, programmatically clicks the "Overview" tab
   * to prevent the user from landing on a now-hidden tab.
   *
   * @param {HTMLElement} selectTrainingStructureElement
   *   The <select> element for field_training_structure.
   * @param {Array<string>} main_training_groups
   *   Field group machine names shown only for non-instance (main) trainings.
   * @param {Array<string>} main_training_fields
   *   Field machine names shown only for non-instance (main) trainings.
   * @param {Array<string>} instance_training_groups
   *   Field group machine names shown only for instance trainings.
   * @param {Array<string>} instance_training_fields
   *   Field machine names shown only for instance trainings.
   */
  function updateTrainingEditFormUIByTrainingstructure(
    selectTrainingStructureElement,
    main_training_groups,
    main_training_fields,
    instance_training_groups,
    instance_training_fields
  ) {
    let trainingStructureVal = $(selectTrainingStructureElement).val();
    if (trainingStructureVal === 'instance') {
      hideGroupDetails(main_training_groups);
      hideFieldWrapper(main_training_fields);
      showGroupDetails(instance_training_groups);
      showFieldWrapper(instance_training_fields);
    }
    else {
      hideGroupDetails(instance_training_groups);
      hideFieldWrapper(instance_training_fields);
      showGroupDetails(main_training_groups);
      showFieldWrapper(main_training_fields);
    }

    // Return focus to the Overview tab so the user is never left
    // on a tab that has just been hidden.
    $('a[href="#edit-group-overview"]')[0]?.click();
  }

  /**
   * Placeholder behavior for future node form conditional field logic.
   *
   * @type {Drupal~behavior}
   */
  Drupal.behaviors.nodeFormConditionalFields = {
    attach: function (context) {
      // Reserved for additional conditional field behaviors.
    },
  };

  /**
   * Toggles field groups and fields based on the training structure select.
   *
   * Uses once() to ensure the change listener and initial UI setup are only
   * attached once per select element, even if Drupal.attachBehaviors() is
   * called multiple times (e.g. after AJAX rebuilds).
   *
   * Field groups and fields are divided into two sets:
   *  - Main training:    group_gallery, field_featured_image
   *  - Instance training: competency, objectives, methods, modules,
   *                        KYC groups; parent training, venue, date, duration
   *
   * @type {Drupal~behavior}
   */
  Drupal.behaviors.trainingStructureChange = {
    attach: function (context) {
      once('trainingStructureChange', 'select[name="field_training_structure"]', context)
        .forEach(function (selectTrainingStructureElement) {

          // Field groups visible only on instance trainings.
          let instance_training_groups = [
            'group_gallery',
            'group_participants'
          ];

          // Fields visible only on instance trainings.
          let instance_training_fields = [
            'field_parent_training',
            'field_venue',
            'field_date_range',
            'field_duration',
            'field_course_coodinator'
          ];

          // Field groups visible only on main (non-instance) trainings.
          let main_training_groups = [
            'group_competency_framework',
            'group_course_objectives',
            'group_training_methods',
            'group_course_modules_and_classro',
            'group_kyc',
          ];

          // Fields visible only on main (non-instance) trainings.
          let main_training_fields = [
            'field_short_name',
            'field_featured_image',
            'field_contact_person'
          ];

          // Set the correct initial UI state on page load before any
          // user interaction, based on the field's current value.
          updateTrainingEditFormUIByTrainingstructure(
            selectTrainingStructureElement,
            main_training_groups,
            main_training_fields,
            instance_training_groups,
            instance_training_fields
          );

          // Re-evaluate and reapply visibility rules on every change.
          $(selectTrainingStructureElement).on('change', function () {
            updateTrainingEditFormUIByTrainingstructure(
              this,
              main_training_groups,
              main_training_fields,
              instance_training_groups,
              instance_training_fields
            );
          });

        });
    },
  };


  /**
   * Training Participant Group Filter
   */
  Drupal.behaviors.trainingParticipantGroupFilter = {

    /**
     * Attach behavior to the participant group filter wrapper.
     *
     * Initializes the participant group filter UI by:
     * - Hiding the raw text input and replacing it with dynamic radio buttons.
     * - Populating radio options from existing participant group select fields.
     * - Listening for changes to sync the filter state and show/hide rows.
     *
     * @param {HTMLElement} context - The DOM context provided by Drupal.
     */
    attach: function (context) {

      /** @type {string} Reserved for future use (e.g. storing a reference to the active radio button). */
      let groupRadioBtn = '';

      /** @type {string[]} Tracks group values already added as radio options to prevent duplicates. */
      let selectedGroupValues = [];

      /**
       * Adds a radio button option to the participant group filter list.
       *
       * Creates the filter option list wrapper if it does not yet exist.
       * Skips insertion if an option with the same value already exists.
       *
       * @param {string} value - The option value (e.g. a group ID or 'all').
       * @param {string} label - The human-readable label for the radio button.
       * @param {boolean} active - To make the radio button active.
       */
      function addParticipantGroupFilterOption(value, label, active = false) {
        // Prevent duplicate radio buttons for the same value.
        if ($('#participant-group-filter-' + value).length) {
          return;
        }

        let checked = '';
        if (active) {
          checked = 'checked';
        }

        const option = `
        <div class="form-type--radio form-type--boolean participant-group-filter-option">
          <input
            type="radio"
            name="training_participant_group_filter"
            value="${value}"
            class="form-radio form-boolean form-boolean--type-radio"
            id="participant-group-filter-${value}"
            ${checked}
          >
          <label
            for="participant-group-filter-${value}"
            class="form-item__label option"
          >
            ${label}
          </label>
        </div>
      `;

        const $wrapperId = 'training-participant-group-filter-option-list';
        let $participantGroupFilterOption = $('#' + $wrapperId);

        // Create the radio group wrapper if it doesn't exist yet.
        if (!$participantGroupFilterOption.length) {
          $('#edit-field-participant-group-filter-wrapper').append(`
          <div
            id="${$wrapperId}"
            class="form-radios form-boolean-group participant-group-filter-option-list"
          ></div>
        `);
          $participantGroupFilterOption = $('#' + $wrapperId);
        }

        $participantGroupFilterOption.append(option);
      }

      /**
       * Shows or hides a participant row based on the active filter value.
       *
       * A row is visible if:
       * - The filter is set to 'all' or is empty (no filter active), or
       * - The row's group value matches the current filter value, or
       * - The row's group value is empty or '_none' (unassigned rows always show).
       *
       * @param {jQuery} $element  - The group <select> element within the participant row.
       * @param {string} currentFilterValue - The currently selected filter value.
       */
      function participationListHideShow($element, currentFilterValue) {
        const value = $element.val();
        const $row = $element.closest('tr.paragraph-type--participant');

        if (
          currentFilterValue === value ||
          currentFilterValue === 'all' ||
          currentFilterValue === '' ||
          value === '' ||
          value === '_none'
        ) {
          $row.show();
        } else {
          $row.hide();
        }
      }

      // Initialize the filter wrapper once: hide the raw text input and add the default 'All' radio option.
      once('participant-group-filter-option', '#edit-field-participant-group-filter-wrapper', context)
        .forEach(function (participantGroupFilter) {
          const $wrapper = $(participantGroupFilter);
          const $input = $wrapper.find('input[type="text"]');
          $input.hide();
          addParticipantGroupFilterOption('all', 'All');
        });

      // Process each participant group <select> field once:
      // - Register its current value as a filter radio option.
      // - Listen for changes to dynamically add new options as groups are selected.
      // - Apply the current filter to show/hide its row on load.
      once('participant-group-option', 'select[data-drupal-selector$="subform-field-participant-group"]', context)
        .forEach(function (element) {
          const $selectParticipantGroup = $(element);
          const value = $selectParticipantGroup.val();
          const label = $selectParticipantGroup.find('option:selected').text();

          // Apply the currently active filter to this row on initial page load.
          const currentParticipantGroupFilter = $('input[name="field_participant_group_filter[0][value]"]').val();
          participationListHideShow($selectParticipantGroup, currentParticipantGroupFilter);

          // Add a radio option for the pre-selected group value if not already tracked.
          if (value && value !== '_none' && !selectedGroupValues.includes(value)) {
            selectedGroupValues.push(value);
            addParticipantGroupFilterOption(value, label, value == currentParticipantGroupFilter);
          }

          // When the user changes a participant's group, register the new value as a filter option.
          $selectParticipantGroup.on('change', function () {
            const value = $(this).val();
            const label = $(this).find('option:selected').text();

            if (value && value !== '_none' && !selectedGroupValues.includes(value)) {
              selectedGroupValues.push(value);
              addParticipantGroupFilterOption(value, label, value == currentParticipantGroupFilter);
            }
          });

        });

      // Listen for filter radio button changes within the participants wrapper and:
      // - Persist the selected filter value to the hidden field.
      // - Re-evaluate visibility of all participant rows against the new filter.
      once('detail-group-participants-wrapper', '#edit-group-participants', context)
        .forEach(function (element) {
          const $wrapper = $(element);

          $wrapper.on('change', 'input[name="training_participant_group_filter"]', function () {
            const currentFilterValue = $(this).val();

            // Sync the selected filter value to the underlying hidden/text field.
            $wrapper
              .find('input[name="field_participant_group_filter[0][value]"]')
              .val(currentFilterValue)
              .trigger('change');

            // Show or hide each participant row based on the updated filter.
            const $participantGroupSelects = $wrapper.find(
              '#edit-field-participants-wrapper .paragraph-type--participant select[data-drupal-selector$="subform-field-participant-group"]'
            );

            $participantGroupSelects.each(function () {
              participationListHideShow($(this), currentFilterValue);
            });
          });
        });

    },

  };

})(jQuery, Drupal, drupalSettings, once);